# File Generator: Creates scalable, context-aware content for files.

import string
import random
import itertools
from pathlib import Path
from typing import Iterator

# --- Configuration & Helpers ---

# Although the primary chunking is based on logical blocks (functions),
# this defines a general buffer size for potential intermediate buffering.
CHUNK_SIZE = 4 * 1024 * 1024  # 4MB chunks for streamed writes

def _generate_python_like_block(target_length: int) -> Iterator[str]:
    """Generates simulated Python code content in chunks up to target_length.
    This improves memory handling over generating one massive string.
    """
    # Initial boilerplate
    content_template = [
        "# This module was auto-generated by Sovereign AGI v94.1 for codebase simulation.",
        "import logging",
        "import typing",
        "",
        "class SimulatedAPIComponent(typing.Protocol):",
        "    ""A large component designed for stress testing evolution analysis.""",
        "    def initialize_state(self, configuration_id: str) -> bool: ...",
        "",
    ]
    
    current_length = sum(len(line) + 1 for line in content_template) # +1 for newline

    yield '\n'.join(content_template) + '\n'

    # Generate random functions to reach target size
    func_counter = itertools.count(1)
    
    while current_length < target_length:
        func_id = next(func_counter)
        
        # Standard formatting for function name (e.g., handler_v00001)
        func_name = f"handler_v{func_id:05d}"
        docstring = f'    """Handles workload {func_id}, generated by the AGI."""'
        
        # Generate parameters (a, b, c...) based on the function index
        params = ', '.join(random.choices(string.ascii_lowercase, k=random.randint(1, 4)))
        
        function_def = [
            f"    def {func_name}(self, {params}):",
            docstring,
            # Use constant func_id within the generated code string for static reference
            f"        # Log the static identifier generated by the file creator.",
            f"        logging.debug(f'Running function {func_name} with id: {func_id}')",
            f"        if {func_id} % 7 == 0:",
            f"            # Placeholder logic branch to simulate complexity\n            self.update_metadata({func_id})",
            f"        return {{'status': 'processed', 'id': {func_id}}}",
            "",
        ]
        
        block = '\n'.join(function_def) + '\n'
        block_len = len(block)
        
        if current_length + block_len > target_length and func_id > 1:
            # Prevent significant overshoot by terminating before the last full block
            break 
            
        current_length += block_len
        yield block


def create_py_files_streamed(num_files: int, target_dir: str, target_length: int) -> None:
    """
    Creates multiple .py files using chunked streaming for large files,
    improving memory efficiency.
    """
    output_path = Path(target_dir)
    output_path.mkdir(exist_ok=True, parents=True)
    
    print(f"\nGenerating {num_files} files of {target_length / (1024*1024):.2f}MB each in '{{target_dir}}'...")

    for i in range(num_files):
        filename = f'candidate_{i:03d}.py'
        filepath = output_path / filename
        
        bytes_written = 0
        
        # Initialize content generator
        content_generator = _generate_python_like_block(target_length)
        
        try:
            # Use standard 'w' mode and explicit encoding for text content robustness
            with open(filepath, 'w', encoding='utf-8') as file:
                for chunk in content_generator:
                    if bytes_written >= target_length:
                        break 

                    chunk_len = len(chunk)
                    
                    if bytes_written + chunk_len > target_length:
                        # If the last chunk is too big, trim it precisely.
                        remaining = target_length - bytes_written
                        file.write(chunk[:remaining])
                        bytes_written += remaining
                        break
                    else:
                        file.write(chunk)
                        bytes_written += chunk_len

            print(f'Created file: {filename} ({bytes_written} bytes) SUCCESS')

        except IOError as e:
            print(f"Error writing file {filename}: {e} FAILURE")
            
# Usage
if __name__ == '__main__':
    # Example parameters optimized for fast local execution while maintaining structural validity.
    NUM_FILES = 10 
    FILE_LENGTH = 5 * 1024 * 1024  # 5MB file length
    TARGET_DIR = 'candidates_simulated'
    
    create_py_files_streamed(
        num_files=NUM_FILES, 
        target_dir=TARGET_DIR, 
        target_length=FILE_LENGTH
    )