module.exports = {
  content: [
    './pages/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-serif)', 'Georgia', 'serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      fontSize: {
        xs: {
          fontSize: 'clamp(0.75rem, 0.7rem + 0.15vw, 0.875rem)',
          lineHeight: '1.4',
        },
        sm: {
          fontSize: 'clamp(0.875rem, 0.8rem + 0.2vw, 1rem)',
          lineHeight: '1.5',
        },
        base: {
          fontSize: 'clamp(1rem, 0.95rem + 0.25vw, 1.125rem)',
          lineHeight: '1.6',
        },
        lg: {
          fontSize: 'clamp(1.125rem, 1.05rem + 0.3vw, 1.25rem)',
          lineHeight: '1.5',
        },
        xl: {
          fontSize: 'clamp(1.25rem, 1.15rem + 0.4vw, 1.5rem)',
          lineHeight: '1.4',
        },
        '2xl': {
          fontSize: 'clamp(1.5rem, 1.35rem + 0.6vw, 2rem)',
          lineHeight: '1.3',
        },
        '3xl': {
          fontSize: 'clamp(1.875rem, 1.65rem + 0.9vw, 2.5rem)',
          lineHeight: '1.2',
        },
        '4xl': {
          fontSize: 'clamp(2.25rem, 1.95rem + 1.2vw, 3.5rem)',
          lineHeight: '1.1',
        },
        '5xl': {
          fontSize: 'clamp(3rem, 2.5rem + 2vw, 4.5rem)',
          lineHeight: '1',
        },
      },
      spacing: {
        0.5: '0.125rem',
        1.5: '0.375rem',
        2.5: '0.625rem',
        3.5: '0.875rem',
        4.5: '1.125rem',
        5.5: '1.375rem',
        6.5: '1.625rem',
        7.5: '1.875rem',
        8.5: '2.125rem',
        9.5: '2.375rem',
        13: '3.25rem',
        15: '3.75rem',
        17: '4.25rem',
        18: '4.5rem',
        19: '4.75rem',
        21: '5.25rem',
        22: '5.5rem',
        23: '5.75rem',
        25: '6.25rem',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
        inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
      },
      transitionDuration: {
        DEFAULT: '220ms',
        fast: '150ms',
        slow: '300ms',
      },
      keyframes: {
        fade_in: { '0%': { opacity: 0 }, '100%': { opacity: 1 } },
        fade_out: { '0%': { opacity: 1 }, '100%': { opacity: 0 } },
        slide_in_top: { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(0)' } },
        slide_in_bottom: { '0%': { transform: 'translateY(100%)' }, '100%': { transform: 'translateY(0)' } },
        slide_in_left: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(0)' } },
        slide_in_right: { '0%': { transform: 'translateX(100%)' }, '100%': { transform: 'translateX(0)' } },
        scale_in: { '0%': { transform: 'scale(0.95)', opacity: 0 }, '100%': { transform: 'scale(1)', opacity: 1 } },
        spin: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        shimmer: { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        pulse: { '0%, 100%': { opacity: 1 }, '50%': { opacity: 0.5 } },
        bounce: {
          '0%, 100%': { transform: 'translateY(-25%)', animationTimingFunction: 'cubic-bezier(0.8,0,1,1)' },
          '50%': { transform: 'translateY(0)', animationTimingFunction: 'cubic-bezier(0,0,0.2,1)' },
        },
      },
      animation: {
        fade_in: 'fade_in 0.2s ease-out',
        fade_out: 'fade_out 0.2s ease-out',
        slide_in_top: 'slide_in_top 0.3s ease-out',
        slide_in_bottom: 'slide_in_bottom 0.3s ease-out',
        slide_in_left: 'slide_in_left 0.3s ease-out',
        slide_in_right: 'slide_in_right 0.3s ease-out',
        scale_in: 'scale_in 0.2s ease-out',
        spin: 'spin 0.6s linear infinite',
        shimmer: 'shimmer 1.5s ease-in-out infinite',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        bounce: 'bounce 1s infinite',
      },
      zIndex: {
        dropdown: 1000,
        sticky: 1100,
        fixed: 1200,
        'modal-backdrop': 1300,
        modal: 1400,
        popover: 1500,
        tooltip: 1600,
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    {
      addComponents: {
        '.container': {
          width: '100%',
          marginLeft: 'auto',
          marginRight: 'auto',
          paddingLeft: '4rem',
          paddingRight: '4rem',
          '@screen sm': { maxWidth: '640px' },
          '@screen md': { maxWidth: '768px' },
          '@screen lg': { maxWidth: '1024px', paddingLeft: '6rem', paddingRight: '6rem' },
          '@screen xl': { maxWidth: '1280px' },
          '@screen 2xl': { maxWidth: '1536px' },
        },
      },
    },
  ],
};