/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js and should not be edited.
// See https://nextjs.org/docs/app/api-reference/config/typescript for more information.
// We maintain the file structure but slightly improve the explanatory comment.