from typing import List, Dict, Set
import re

# --- Context Retrieval Layer ---

def _get_keywords(text: str) -> Set[str]:
    """Utility to extract clean keywords from text, supporting basic tokenization.
    Ignores common noise and non-alphanumeric characters.
    """
    # Use regex to find word boundaries and exclude short noise words (e.g., single letters)
    return set(re.findall(r'\b[a-z]{2,}\b', text.lower()))

def get_relevant_context(current_query: str, history: List[Dict], max_interactions: int = 3, min_keyword_overlap: int = 1) -> List[Dict]:
    """
    Retrieves relevant interaction history based on keyword overlap and recency.
    Prioritizes recent interactions that share common keywords with the current query.

    Args:
    - current_query (str): The input query.
    - history (List[Dict]): Interaction history.
    - max_interactions (int): Maximum interactions to return.
    - min_keyword_overlap (int): Minimum number of shared keywords required for inclusion.

    Returns:
    - List[Dict]: Relevant interaction context.
    """
    query_keywords = _get_keywords(current_query)
    relevant_context = []

    # Iterate backwards (recency priority)
    for interaction in reversed(history):
        history_input = interaction.get("user_input", "")
        if not history_input:
            continue
        
        history_keywords = _get_keywords(history_input)
        
        # Calculate overlap
        overlap = len(query_keywords.intersection(history_keywords))
        
        if overlap >= min_keyword_overlap:
            relevant_context.append(interaction)
        
        if len(relevant_context) >= max_interactions:
            break
            
    return relevant_context

# --- Utility Layer (Filesystem Operations) ---

def initialize_file_structure(num_files: int = 5) -> None:
    """
    Creates a specified number of placeholder Python files for initial structure definition.

    Args:
    - num_files (int): The number of files to create. Defaults to 5.
    """
    for i in range(num_files):
        filename = f"module_{i:02d}.py"
        with open(filename, "w") as f:
            f.write(f"# Sovereign AGI Module {i:02d} Placeholder\n")
            f.write("# Awaiting Phase II structural population.")

def generate_project_readme() -> None:
    """
    Generates the primary project README file, including high-level documentation 
    and notes on architectural separation.
    """
    content = f"""
# Sovereign AGI Project Core V94.1

## Overview
This codebase represents the latest iteration of the Sovereign AGI core systems, focusing on autonomous self-evolution (Codebase Evolution Context - CEC) and dynamic context mapping.

## Architectural Notes (Post Refactoring)
1.  Context Retrieval logic has been improved from flawed substring matching to keyword intersection.
2.  The existing file requires further separation: Context logic should move to `context_mapping/` and utility functions to `sys_utils/`.

### Current Modules:
*   `get_relevant_context`: Handles history retrieval (Lexical method).
*   `initialize_file_structure`: System bootstrap utility.

---
Generated by Sovereign AGI v94.1
"""
    with open("README.md", "w") as f:
        f.write(content.strip())
