from typing import TypedDict, Optional, Any
import time
import random
import numpy as np
import logging
import uuid
from queue import Queue
import threading
import json
import os
import hashlib
import secrets
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.backends import default_backend
from cryptography.exceptions import InvalidSignature

# --- DEFINITIONS AND TYPE HINTS (Architectural Clarity) ---

class RawPayload(TypedDict):
    """Defines the structure of the data generated by the satellite."""
    id: str
    ts: float
    temp: float
    humidity: float
    checksum: str

class SecurePackage(TypedDict):
    """Defines the structure of the package sent over the simulated channel."""
    payload: str  # JSON dump of RawPayload
    signature: str # Base64 encoded signature

# --- AGI CONTEXTUAL VARIABLES AND SETUP ---

# Secure Channel Simulation: Generate RSA keys once (Private key stays on 'satellite')
PRIVATE_KEY: rsa.RSAPrivateKey = rsa.generate_private_key(
    public_exponent=65537,
    key_size=2048,
    backend=default_backend()
)
PUBLIC_KEY: rsa.RSAPublicKey = PRIVATE_KEY.public_key()
A_KEY_PEM_PUBLIC = PUBLIC_KEY.public_bytes(serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo)
DATA_QUEUE = Queue()

# Configure logging to capture debug/info levels consistently
logging.basicConfig(level=logging.INFO, format='%(levelname)s [%(name)s]: %(message)s')

# --- CRYPTOGRAPHY UTILITIES ---

def sign_data(data: str, private_key: rsa.RSAPrivateKey) -> bytes:
    """Signs the JSON string data using the satellite's private key."""
    data_bytes = data.encode('utf-8')
    signature = private_key.sign(
        data_bytes,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )
    return signature

def verify_data(data: str, signature: bytes, public_key: rsa.RSAPublicKey) -> bool:
    """Verifies the signature of the JSON string data using the public key (receiver side)."""
    data_bytes = data.encode('utf-8')
    try:
        public_key.verify(
            signature,
            data_bytes,
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH
            ),
            hashes.SHA256()
        )
        return True
    except InvalidSignature:
        logging.error("Integrity Failure: Invalid Signature detected.")
        return False

# --- SATELLITE SIMULATION (Producer) ---

def data_simulator_thread(data_queue: Queue, private_key: rsa.RSAPrivateKey):
    """Simulates the satellite transmitting securely signed environmental data.
    Now checks Thomas's status to implement backpressure (throttling)."""
    logging.info(f"Data Simulator active. Simulated Public Key Deployment: {A_KEY_PEM_PUBLIC[:40]}...")

    while True:
        # Simulated environmental readings
        temperature = round(random.uniform(-50.0, 30.0), 2)
        humidity = round(random.uniform(0.0, 100.0), 2)
        timestamp = time.time()
        
        raw_data: RawPayload = {
            "id": str(uuid.uuid4()),
            "ts": timestamp,
            "temp": temperature,
            "humidity": humidity,
            "checksum": hashlib.sha256(f"{temperature:.2f}|{humidity:.2f}|{timestamp}".encode()).hexdigest()[:8]
        }
        
        json_data = json.dumps(raw_data)
        signature = sign_data(json_data, private_key)
        
        # Encode signature for safe JSON transmission
        secure_package: SecurePackage = {
            "payload": json_data,
            "signature": serialization.base64.urlsafe_b64encode(signature).decode('utf-8')
        }
        
        data_queue.put(secure_package)
        logging.debug(f"[SIM] Pushed package {raw_data['checksum']}.")
        
        # Check Thomas's static method for queue pressure
        if Thomas.is_overloaded(data_queue):
             logging.warning("Simulator throttling initiated due to Thomas Alert.")
             time.sleep(random.uniform(5.0, 8.0)) 
        else:
             time.sleep(random.uniform(0.5, 2.0)) 

# --- RECEIVER LOGIC (Consumer) ---

def receive_data_from_satellite(data_queue: Queue, public_key: rsa.RSAPublicKey) -> Optional[RawPayload]:
    """Retrieves and cryptographically validates data from the queue.
    Returns None on integrity failure or decoding error."""
    if data_queue.empty():
        return None

    try:
        # Use non-blocking get
        secure_package: SecurePackage = data_queue.get(block=False)
        payload = secure_package['payload']
        signature_bytes = serialization.base64.urlsafe_b64decode(secure_package['signature'].encode('utf-8'))
        
        if verify_data(payload, signature_bytes, public_key):
            # Successfully validated and typed
            return json.loads(payload)
        else:
            # If validation fails, drop data (already logged in verify_data)
            return None
            
    except Exception as e:
        # Handle structural issues (JSON, base64 decoding)
        if isinstance(e, (json.JSONDecodeError, ValueError)):
             logging.error(f"Integrity Failure: Malformed package data detected. {e}")
        else:
             logging.error(f"Data retrieval or structural error: {e}. Package skipped.")
        return None

def display_data(data: Optional[RawPayload]):
    """Formats and displays the processed environmental data."""
    os.system('cls' if os.name == 'nt' else 'clear') 
    print("\n--- AGI SECURE ENVIRONMENTAL MONITOR v94.1 ---")
    
    if data is None:
        print("Status: Waiting for new transmission... [Queue Empty or Integrity Failed]")
        print("--------------------------------------------------")
        return

    status = "OK"
    
    print(f"[STATUS: {status}] Data ID: {data['id'][:8]}...")
    print("--------------------------------------------------")
    print(f"| Time (UTC): {time.ctime(data['ts'])}")
    print(f"| Temperature: {data['temp']:<8} C")
    print(f"| Humidity: {data['humidity']:<8} %")
    print(f"| Satellite Checksum: {data['checksum']}")
    print("--------------------------------------------------")


def main_receiver_loop(data_queue, public_key):
    print("Starting Real-Time Environmental Data Display...")
    time.sleep(1)
    while True:
        data = receive_data_from_satellite(data_queue, public_key)
        display_data(data)
        time.sleep(1) 

# --- LEGACY/ANOMALY SUB-PROCESS (THOMAS) - Flow Control Agent ---

class Thomas(threading.Thread):
    CRITICAL_THRESHOLD = 15
    
    def __init__(self, data_queue: Queue, interval=5.0):
        super().__init__(daemon=True, name="Thomas-Monitor")
        self.data_queue = data_queue
        self.interval = interval
        logging.info(f"Thomas initialized as Flow Control Agent (Threshold: {self.CRITICAL_THRESHOLD}).")

    @staticmethod
    def is_overloaded(data_queue: Queue) -> bool:
        """Static method used by the Producer thread to check for backpressure conditions."""
        return data_queue.qsize() > Thomas.CRITICAL_THRESHOLD

    def run(self):
        while True:
            q_size = self.data_queue.qsize()
            if q_size < 5:
                logging.debug(f"[THOMAS]: Queue size {q_size}. System running lean.")
            elif q_size <= self.CRITICAL_THRESHOLD:
                logging.info(f"[THOMAS]: Queue size {q_size}. Optimal throughput maintained.")
            else:
                # This log indicates that the simulator should already be throttling
                logging.critical(f"[THOMAS] CRITICAL ALERT! Persistent Queue Overflow ({q_size} items).")
            time.sleep(self.interval)

if __name__ == "__main__":
    # 1. Start the persistent diagnostic and flow control agent (Thomas)
    thomas_agent = Thomas(DATA_QUEUE, interval=5.0)
    thomas_agent.start()

    # 2. Simulate satellite data production in a separate thread
    satellite_thread = threading.Thread(target=data_simulator_thread, args=(DATA_QUEUE, PRIVATE_KEY), daemon=True, name="Satellite-Simulator")
    satellite_thread.start()

    # 3. Start the main receiver and display loop
    try:
        main_receiver_loop(DATA_QUEUE, PUBLIC_KEY)
    except KeyboardInterrupt:
        print("\nAGI Shutdown initiated.")
        exit(0)