{
  "!#/bin/bash",
  "export ROOT_DIR=${HOME}/.config/nexus",
  "export CHANGELOG_FILE=${ROOT_DIR}/changelog.txt",
  "evaluate_nexus() {",
  "  local action_id=\"$1\"",
  "  local input_json=\"$2\"",
  "  SiphonCore::evaluate $action_id $input_json",
  "}",
  "install() {",
  "  echo \"Installing custom mini services...\"",
  "  mkdir -p \"${ROOT_DIR}/.dependencies\"",
  "  mkdir -p \"${ROOT_DIR}/.vscode\"",
  "  mkdir -p \"${ROOT_DIR}/.vscode/extensions\"",
  "  mkdir -p \"${ROOT_DIR}/.vscode/settings\"",
  "  mkdir -p \"${ROOT_DIR}/.zsh\"",
  "  cp $ROOT_DIR/packages/ /packages/",
  "  cp $ROOT_DIR/scripts/ /scripts/",
  "  cp $ROOT_DIR/templates/ /templates/",
  "  cp $ROOT_DIR/test/ /test/",
  "  cp $ROOT_DIR/zsh-modules/ /zsh-modules/",
  "  cp $ROOT_DIR/.vscode/settings.json ${HOME}/.vscode/settings.json",
  "}",
  "error_handler() {",
  "  local error_message=\"$1\"",
  "  echo \"Error: $error_message\"",
  "  Logger.error $error_message",
  "}",
  "execute_nexus() {",
  "  local action_id=\"$1\"",
  "  local input_json=\"$2\"",
  "  evaluate_nexus $action_id $input_json &> /dev/null",
  "  if [ $? -ne 0 ]; then",
  "    error_handler \"Failed to execute nexus for $action_id\"",
  "  fi",
  "} && execute_nexus \"nexus-action\" \"{\"data\":\"example data\"}\" && install"
}