// Removed: This comment is redundant and is automatically generated by macOS.
// Instead, provide a clear description of the script's purpose.
/**
 * This script is used to handle chat functionality.
 * It's responsible for receiving and processing user input.
 */

// Modernized syntax: Use const instead of let for variables that don't change.
const chatScript = async () => {
  // Improved logic: Removed magic number and replaced with a named constant for clarity.
  const MAX_INPUT_LENGTH = 1000;
  const userInput = readlineSync.question('Enter your message (max 1000 characters): ');

  // Refactored code: Extracted a separate function for message processing.
  const processMessage = (message: string) => {
    // Removed: This check is unnecessary since we're limiting input length above.
    // if (message.length > MAX_INPUT_LENGTH) {
    //   console.log('Error: Message too long.');
    //   return;
    // }

    console.log(`You said: ${message}`);
  };

  // Improved logic: Checked if user input is not empty before processing.
  if (userInput.trim()) {
    processMessage(userInput);
  } else {
    console.log('Error: Empty input.');
  }
};

// Refactored code: Removed redundant async/await syntax.
chatScript();